# Generated by Django 5.0.2 on 2024-03-18 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_video_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='video',
            name='duration_seconds',
        ),
    ]
