# Generated by Django 5.0.2 on 2024-03-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_alter_video_likes_alter_video_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='article3',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='news',
            name='title1',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title2',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title3',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
